In [13]:
import numpy as np

In [14]:
z = np.array([[1, 0], [0, -1]])
i = np.eye(2)

In [15]:
from functools import reduce

In [16]:
reduce(np.kron, [z, z, i]) + reduce(np.kron, [z, i, z])

array([[ 2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -2.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -2., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.]])

In [17]:
def kron(fac:list):
    return reduce(np.kron, fac)

$$ Z_1 Z_2 + Z_1 Z_3 $$

In [18]:
np.diag(kron([z, z, i]) + kron([z, i, z]))

array([ 2.,  0.,  0., -2., -2.,  0.,  0.,  2.])

$$ Z_1 Z_2 + Z_1 Z_3 + Z_2 Z_3 $$

In [19]:
np.diag(kron([z, z, i]) + kron([z, i, z]) + kron([i, z, z]))

array([ 3., -1., -1., -1., -1., -1., -1.,  3.])

$더하는~횟수와~Hamiltonian이~일치하지~않음$

$\Rightarrow$  $H = \sum _{(i, j)} ^{n} I - Z_i Z_j$ $로~정의$